### ISSUE TITLE
Add a button

### ISSUE THREAD

**Issue by anasvakyathodi** [anasvakyathodi/Dog-Book#1]
Add a button in the list item... which which should work as:  

-  Select the item and store into a state (already a function created)
-  After storing the value, it should redirect to the second tab which contains Dog image

**Comment by nehathakur27** [comment]
Hey, I would like to contribute. Can you please explain me the task?

**Comment by anasvakyathodi** [comment]
> Hey, I would like to contribute. Can you please explain me the task?

- Create a mui button called "select" in list view of breeds (on the first tab)
- button can be inside the list along with sub-breed option.

Functionalities of button:

On click : 

- add the current breed name into a state (this function is already in the module without any button)
- goto 2nd tab (which contains the image of the selected dog)


![image](https://user-images.githubusercontent.com/44634141/95459146-d9dcd100-0990-11eb-9942-b9a3a51a8044.jpeg)

![image](https://user-images.githubusercontent.com/44634141/95459156-dea18500-0990-11eb-8561-bc31174617a4.jpeg)

Thank you and good luck :)

**Comment by nehathakur27** [comment]
Is the issue resolved?

**Comment by anasvakyathodi** [comment]
> Is the issue resolved?

Yeah @web2feel did it... Don't worry so many issues are made for hacktoberfest. Checkout another hacktoberfest issue on my git.
