### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by anasvakyathodi** [anasvakyathodi/Dog-Book#11]
Add Contributors list with their github names or username which is linked to their corresponding git account.

**Comment by negiankit97** [comment]
@anasvakyathodi  I'd like to work on this issue.

**Comment by anasvakyathodi** [comment]
Thanks for your contribution... and It's working perfectly.

it will be better if,
-  reducing size or change typography variant into small font styles

- remove repeating "developed by" and "contributor" caption

- make a heading contributors, it will make better view

- make the git url a button icon (like github button icon) which will reduce the size and make it look better

![dog-book](https://user-images.githubusercontent.com/44634141/97557391-b988bb00-1a00-11eb-9785-546ef729bf43.jpg)
<img width="255" alt="model" src="https://user-images.githubusercontent.com/44634141/97558215-d2de3700-1a01-11eb-80b6-c71c129a9bce.png">
this is a rough figure... that I thought of making in about section

**Comment by anasvakyathodi** [comment]
Hope you understand what I meant :)
