### ISSUE TITLE
Back-To-Top button on the Breeds Page.

### ISSUE THREAD

**Issue by Bhargav252000** [anasvakyathodi/Dog-Book#12]
We can add Back-to-top button on the Breeds page, it will make easy to go back to top of the page.

**Comment by anasvakyathodi** [comment]
> 
> 
> We can add Back-to-top button on the Breeds page, it will make easy to go back to top of the page.

Do you want to do it ?

**Comment by Bhargav252000** [comment]
#13 Pull Request Created for the same
