### ISSUE TITLE
Add a search field

### ISSUE THREAD

**Issue by anasvakyathodi** [anasvakyathodi/Dog-Book#3]
Add a MUI search field
Conditions:
- Its position must be above Accordions and below tab menu
- there must be a function which filter the list onchanging the field text

**Comment by alexandramj92** [comment]
I am interested in taking on this issue. Can you assign me to it?

**Comment by anasvakyathodi** [comment]
> I am interested in taking on this issue. Can you assign me to it?

Sure lady ! Here you go 🔥
