### ISSUE TITLE
React-loader on image

### ISSUE THREAD

**Issue by anasvakyathodi** [anasvakyathodi/Dog-Book#4]
1.while selecting any breed, it takes some secs to load image
2. Add a react-loader which is centered in the image container.

**Comment by chetangawai** [comment]
@anasvakyathodi Can you please assign me this issue?

**Comment by anasvakyathodi** [comment]
> @anasvakyathodi Can you please assign me this issue?

Sure lady !!! Here you go 🔥

**Comment by anasvakyathodi** [comment]
@chetangawai Hey.. Just for confirmation, are you working on this?

**Comment by chetangawai** [comment]
@anasvakyathodi Sorry, cannot take over. I have unassigned myself.

**Comment by anasvakyathodi** [comment]
> @anasvakyathodi Sorry, cannot take over. I have unassigned myself.

That's ok.

**Comment by Bhargav252000** [comment]
Hey @chetangawai can I work on this issue ?

**Comment by Bhargav252000** [comment]
hey @anasvakyathodi  can I work on this issue ?

**Comment by anasvakyathodi** [comment]
> 
> 
> hey @anasvakyathodi can I work on this issue ?
Sure @Bhargav252000
